# Generated by Django 5.2.1 on 2026-03-02 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to send the invitation', max_length=254)),
                ('role', models.CharField(choices=[('hospital_admin', 'Hospital Administrator'), ('ministry_admin', 'Ministry of Health Administrator')], max_length=50)),
                ('token', models.CharField(help_text='Unique token for invitation link', max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message to include in invitation email')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expiration timestamp')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('hospital', models.ForeignKey(blank=True, help_text='Hospital this admin will manage (required for hospital_admin role)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_invitations', to='facilities.hospital')),
                ('invited_by', models.ForeignKey(help_text='User who sent this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin invitation',
                'verbose_name_plural': 'admin invitations',
                'db_table': 'admin_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='admin_invit_email_a1afdb_idx'), models.Index(fields=['token'], name='admin_invit_token_8e716f_idx'), models.Index(fields=['status'], name='admin_invit_status_c6f5b5_idx'), models.Index(fields=['hospital'], name='admin_invit_hospita_5bbc37_idx')],
            },
        ),
    ]
