# Generated by Django 5.2.7 on 2026-01-07 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_push', models.BooleanField(default=True)),
                ('enable_email', models.BooleanField(default=True)),
                ('enable_sms', models.BooleanField(default=False)),
                ('enabled_types', models.JSONField(blank=True, default=dict, help_text="Dictionary of notification types and whether they're enabled")),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('daily_digest', models.BooleanField(default=False, help_text='Receive daily digest instead of individual notifications')),
                ('digest_time', models.TimeField(blank=True, help_text='Time to send daily digest', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment_created', 'Appointment Created'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('medical_book_updated', 'Medical Book Updated'), ('visit_completed', 'Visit Completed'), ('clinical_note_added', 'Clinical Note Added'), ('diagnosis_added', 'New Diagnosis'), ('prescription_created', 'New Prescription'), ('prescription_dispensed', 'Prescription Dispensed'), ('prescription_refill_due', 'Prescription Refill Due'), ('lab_order_created', 'Lab Order Created'), ('lab_sample_collected', 'Lab Sample Collected'), ('lab_result_ready', 'Lab Result Ready'), ('lab_result_abnormal', 'Abnormal Lab Result'), ('admission_created', 'Hospital Admission'), ('discharge_ready', 'Discharge Ready'), ('medical_book_access_granted', 'Medical Book Access Granted'), ('medical_book_access_revoked', 'Medical Book Access Revoked'), ('facility_verified', 'Facility Verified'), ('facility_suspended', 'Facility Suspended'), ('staff_added', 'Staff Member Added'), ('moh_alert', 'Ministry of Health Alert'), ('moh_bulletin', 'Health Bulletin'), ('system_maintenance', 'System Maintenance'), ('account_update', 'Account Update')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('related_object_type', models.CharField(blank=True, help_text='Model name of related object', max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification (URLs, IDs, etc.)')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_push', models.BooleanField(default=False, help_text='Sent via push notification')),
                ('sent_email', models.BooleanField(default=False, help_text='Sent via email')),
                ('sent_sms', models.BooleanField(default=False, help_text='Sent via SMS')),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when clicked', max_length=500)),
                ('action_label', models.CharField(blank=True, help_text='Label for action button', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification expires', null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_498289_idx')],
            },
        ),
    ]
