# Generated by Django 5.2.7 on 2026-01-07 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Secure random token (hashed)', max_length=64, unique=True)),
                ('display_token', models.CharField(help_text='Short display token for UI', max_length=12, unique=True)),
                ('token_type', models.CharField(choices=[('single_use', 'Single Use'), ('time_limited', 'Time Limited'), ('permanent', 'Permanent'), ('multi_use', 'Multi-Use (Limited Count)')], default='time_limited', max_length=20)),
                ('permission_level', models.CharField(choices=[('view_only', 'View Only'), ('view_edit', 'View and Edit'), ('view_vitals', 'View Vitals Only'), ('view_prescriptions', 'View Prescriptions Only'), ('view_lab_results', 'View Lab Results Only'), ('emergency_access', 'Emergency Access (Full)')], default='view_only', max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When token expires (null for permanent)', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of uses (null for unlimited)', null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, help_text='Purpose or description of this token', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (facility info, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_qr_tokens', to=settings.AUTH_USER_MODEL)),
                ('medical_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='medical_records.medicalbook')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_qr_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR token',
                'verbose_name_plural': 'QR tokens',
                'db_table': 'qr_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_by_email', models.EmailField(blank=True, help_text='Email of accessor (for unauthenticated users)', max_length=254)),
                ('permission_level', models.CharField(max_length=30)),
                ('access_result', models.CharField(choices=[('granted', 'Access Granted'), ('denied', 'Access Denied'), ('expired', 'Token Expired'), ('revoked', 'Token Revoked'), ('invalid', 'Invalid Token')], default='granted', max_length=20)),
                ('access_type', models.CharField(default='qr_scan', help_text='How access was attempted (qr_scan, api, manual)', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('geolocation', models.JSONField(blank=True, help_text='Geolocation data (lat, lon, address)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (facility, reason, etc.)')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accessed_by', models.ForeignKey(blank=True, help_text='User who accessed (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_accesses', to=settings.AUTH_USER_MODEL)),
                ('medical_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_access_logs', to='medical_records.medicalbook')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='qr_access.qrtoken')),
            ],
            options={
                'verbose_name': 'QR access log',
                'verbose_name_plural': 'QR access logs',
                'db_table': 'qr_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qrtoken',
            index=models.Index(fields=['medical_book', 'is_active'], name='qr_tokens_medical_3afdd3_idx'),
        ),
        migrations.AddIndex(
            model_name='qrtoken',
            index=models.Index(fields=['token', 'is_active'], name='qr_tokens_token_96ce5a_idx'),
        ),
        migrations.AddIndex(
            model_name='qrtoken',
            index=models.Index(fields=['created_by', '-created_at'], name='qr_tokens_created_e420d4_idx'),
        ),
        migrations.AddIndex(
            model_name='qraccesslog',
            index=models.Index(fields=['medical_book', '-accessed_at'], name='qr_access_l_medical_36128a_idx'),
        ),
        migrations.AddIndex(
            model_name='qraccesslog',
            index=models.Index(fields=['token', '-accessed_at'], name='qr_access_l_token_i_b9fab0_idx'),
        ),
        migrations.AddIndex(
            model_name='qraccesslog',
            index=models.Index(fields=['accessed_by', '-accessed_at'], name='qr_access_l_accesse_316a70_idx'),
        ),
    ]
